-- MySQL Script generated by MySQL Workbench
-- Sat Mar  2 15:15:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project_star_model
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `project_star_model` ;

-- -----------------------------------------------------
-- Schema project_star_model
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_star_model` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `project_star_model` ;

-- -----------------------------------------------------
-- Table `project_star_model`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`cargos` (
  `cargo_nombre` VARCHAR(100) NULL DEFAULT NULL,
  `cargo_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`cargo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`empresa` (
  `empresa_nombre` VARCHAR(100) NULL DEFAULT NULL,
  `empresa_origen` VARCHAR(100) NULL DEFAULT NULL,
  `empresa_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`empresa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`egresado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`egresado` (
  `egresado_names` VARCHAR(100) NULL DEFAULT NULL,
  `egresado_firstlastname` VARCHAR(100) NULL DEFAULT NULL,
  `egresado_secondlastname` VARCHAR(100) NULL DEFAULT NULL,
  `egresado_gender` VARCHAR(10) NULL DEFAULT NULL,
  `egresado_etnicgroup` VARCHAR(10) NULL DEFAULT NULL,
  `egresado_cellphone` VARCHAR(10) NULL DEFAULT NULL,
  `egresado_address` VARCHAR(255) NULL DEFAULT NULL,
  `egresado_emailaddress` VARCHAR(200) NULL DEFAULT NULL,
  `egresado_edad` INT NULL DEFAULT NULL,
  `egresado_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`egresado_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`time_`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`time_` (
  `year_` INT NULL DEFAULT NULL,
  `month_` INT NULL DEFAULT NULL,
  `day_` INT NULL DEFAULT NULL,
  `date_id` DATE NOT NULL,
  INDEX `idx_date_id` (`date_id` ASC) VISIBLE,
  PRIMARY KEY (`date_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`contrataciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`contrataciones` (
  `cargo_id` INT NULL DEFAULT NULL,
  `empresa_id` INT NULL DEFAULT NULL,
  `egresado_id` INT NULL DEFAULT NULL,
  `date_id` DATE NULL DEFAULT NULL,
  `salario` DECIMAL(10,0) NULL DEFAULT NULL,
  `contratacion_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`contratacion_id`),
  INDEX `cargo_id` (`cargo_id` ASC) VISIBLE,
  INDEX `empresa_id` (`empresa_id` ASC) VISIBLE,
  INDEX `egresado_id` (`egresado_id` ASC) VISIBLE,
  INDEX `date_id` (`date_id` ASC) VISIBLE,
  CONSTRAINT `contrataciones_ibfk_1`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `project_star_model`.`cargos` (`cargo_id`),
  CONSTRAINT `contrataciones_ibfk_2`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `project_star_model`.`empresa` (`empresa_id`),
  CONSTRAINT `contrataciones_ibfk_3`
    FOREIGN KEY (`egresado_id`)
    REFERENCES `project_star_model`.`egresado` (`egresado_id`),
  CONSTRAINT `contrataciones_ibfk_4`
    FOREIGN KEY (`date_id`)
    REFERENCES `project_star_model`.`time_` (`date_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`departamento` (
  `departamento_nombre` VARCHAR(200) NULL DEFAULT NULL,
  `departamento_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`departamento_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`facultad` (
  `facultad_nombre` VARCHAR(100) NULL DEFAULT NULL,
  `facultad_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`facultad_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`sede_universidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`sede_universidad` (
  `sede_nombre` VARCHAR(50) NULL DEFAULT NULL,
  `sede_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`sede_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`programa` (
  `programa_nombre` VARCHAR(200) NULL DEFAULT NULL,
  `programa_nivelacademico` VARCHAR(50) NULL DEFAULT NULL,
  `programa_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`programa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`graduaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`graduaciones` (
  `sede_id` INT NULL DEFAULT NULL,
  `departamento_id` INT NULL DEFAULT NULL,
  `facultad_id` INT NULL,
  `programa_id` INT NULL DEFAULT NULL,
  `egresado_id` INT NULL DEFAULT NULL,
  `date_id` DATE NULL DEFAULT NULL,
  `registration_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`registration_id`),
  INDEX `sede_id` (`sede_id` ASC) VISIBLE,
  INDEX `departamento_id` (`departamento_id` ASC) VISIBLE,
  INDEX `programa_id` (`programa_id` ASC) VISIBLE,
  INDEX `egresado_id` (`egresado_id` ASC) VISIBLE,
  INDEX `date_id` (`date_id` ASC) VISIBLE,
  INDEX `fk_graduaciones_facultad1_idx` (`facultad_id` ASC) VISIBLE,
  CONSTRAINT `graduaciones_ibfk_1`
    FOREIGN KEY (`sede_id`)
    REFERENCES `project_star_model`.`sede_universidad` (`sede_id`),
  CONSTRAINT `graduaciones_ibfk_2`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `project_star_model`.`departamento` (`departamento_id`),
  CONSTRAINT `graduaciones_ibfk_3`
    FOREIGN KEY (`programa_id`)
    REFERENCES `project_star_model`.`programa` (`programa_id`),
  CONSTRAINT `graduaciones_ibfk_4`
    FOREIGN KEY (`egresado_id`)
    REFERENCES `project_star_model`.`egresado` (`egresado_id`),
  CONSTRAINT `graduaciones_ibfk_5`
    FOREIGN KEY (`date_id`)
    REFERENCES `project_star_model`.`time_` (`date_id`),
  CONSTRAINT `fk_graduaciones_facultad1`
    FOREIGN KEY (`facultad_id`)
    REFERENCES `project_star_model`.`facultad` (`facultad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`institucion` (
  `institucion_nombre` VARCHAR(200) NULL DEFAULT NULL,
  `institucion_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`institucion_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`publicacion` (
  `tipo_publicacion` VARCHAR(100) NULL DEFAULT NULL,
  `ano_publiacion` DATE NULL DEFAULT NULL,
  `descripcion` VARCHAR(1000) NULL DEFAULT NULL,
  `publicacion_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`publicacion_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`revista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`revista` (
  `revista_nombre` VARCHAR(100) NULL DEFAULT NULL,
  `revista_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`revista_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_star_model`.`registro_publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_star_model`.`registro_publicaciones` (
  `publicacion_id` INT NULL DEFAULT NULL,
  `revista_id` INT NULL DEFAULT NULL,
  `institucion_id` INT NULL DEFAULT NULL,
  `egresado_id` INT NULL DEFAULT NULL,
  `date_id` DATE NULL DEFAULT NULL,
  `registration_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`registration_id`),
  INDEX `publicacion_id` (`publicacion_id` ASC) VISIBLE,
  INDEX `revista_id` (`revista_id` ASC) VISIBLE,
  INDEX `institucion_id` (`institucion_id` ASC) VISIBLE,
  INDEX `egresado_id` (`egresado_id` ASC) VISIBLE,
  INDEX `date_id` (`date_id` ASC) VISIBLE,
  CONSTRAINT `registro_publicaciones_ibfk_1`
    FOREIGN KEY (`publicacion_id`)
    REFERENCES `project_star_model`.`publicacion` (`publicacion_id`),
  CONSTRAINT `registro_publicaciones_ibfk_2`
    FOREIGN KEY (`revista_id`)
    REFERENCES `project_star_model`.`revista` (`revista_id`),
  CONSTRAINT `registro_publicaciones_ibfk_3`
    FOREIGN KEY (`institucion_id`)
    REFERENCES `project_star_model`.`institucion` (`institucion_id`),
  CONSTRAINT `registro_publicaciones_ibfk_4`
    FOREIGN KEY (`egresado_id`)
    REFERENCES `project_star_model`.`egresado` (`egresado_id`),
  CONSTRAINT `registro_publicaciones_ibfk_5`
    FOREIGN KEY (`date_id`)
    REFERENCES `project_star_model`.`time_` (`date_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
